#ifndef CONFIG_ELF_DISSECTOR_VERSION_H
#define CONFIG_ELF_DISSECTOR_VERSION_H

#define ELF_DISSECTOR_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define ELF_DISSECTOR_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define ELF_DISSECTOR_VERSION_PATCH ${PROJECT_VERSION_PATCH}

#define ELF_DISSECTOR_VERSION_STRING "${PROJECT_VERSION_STRING}"

#endif
